name: GraalVM Native Image builds
on: [ push, pull_request ]
jobs:
  build:
    name: Target ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ macos-aarch64, macos-amd64, windows-aarch64, windows-amd64, ubuntu-aarch64, ubuntu-amd64, ubuntu-riscv64 ]
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Creating jar package
        run: mvn package

      - name: Creating native image
        run: native-image --target=${{ matrix.target }} -jar target/red-alert-listener-*-jar-with-dependencies.jar

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: red-alert-listener-${{ matrix.target }}
          path: red-alert-listener*
