name: GraalVM Native Image builds
on: [ push, pull_request ]
jobs:
  build:
    name: Target ${{ matrix.os }}-${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
          - os: macos
            architecture: aarch64
          - os: macos
            architecture: amd64
          - os: windows
            architecture: aarch64
          - os: windows
            architecture: amd64
          - os: ubuntu
            architecture: aarch64
          - os: ubuntu
            architecture: amd64
          - os: ubuntu
            architecture: riscv64
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Creating jar package
        run: mvn package

      - name: Creating native image
        run: native-image --target=${{ matrix.os }}-${{ matrix.architecture }} -jar target/red-alert-listener-*-jar-with-dependencies.jar

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: red-alert-listener-${{ matrix.os }}-${{ matrix.architecture }}
          path: red-alert-listener*
