name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Creating jar package
        run: mvn package

      - name: Creating native image
        run: native-image -jar target/red-alert-listener-*-jar-with-dependencies.jar
      
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: red-alert-listener-${{ matrix.os }}
          path: red-alert-listener*
